[workspace]
resolver = "3"
members = ["kursor-core", "kursor", "kursor-fx"]

[workspace.package]
authors = ["vyfor"]
categories = ["command-line-interface"]
keywords = ["terminal", "tui", "cli", "retained", "framework"]
repository = "https://github.com/vyfor/kursor"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
