[package]
name = "kursor-core"
authors.workspace = true
categories.workspace = true
description = "Core runtime and primitives for Kursor"
keywords.workspace = true
license.workspace = true
repository.workspace = true
version = "0.1.0"
edition.workspace = true
readme = "../README.md"

[dependencies]
slab = "0.4"
unicode-width = "0.2"
animate = { version = "0.5", optional = true, default-features = false }

[features]
default = []
animate = ["dep:animate"]