[package]
name = "kursor"
authors.workspace = true
categories.workspace = true
description = "Build reactive terminal interfaces in Rust"
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
readme = "../README.md"

[lib]
crate-type = ["lib"]

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm"]
termina = ["dep:termina"]
animate = ["kursor-core/animate", "dep:animate"]
fx = ["dep:kursor-fx", "animate"]

[dependencies]
kursor-core = { version = "0.1.0", path = "../kursor-core" }
unicode-width = "0.2"
crossterm = { version = "0.29.0", default-features = false, features = ["bracketed-paste", "events"], optional = true }
animate = { version = "0.5", optional = true, default-features = false }
kursor-fx = { version = "0.1.0", path = "../kursor-fx", optional = true }
termina = { version = "0.3.3", optional = true }

[target.'cfg(windows)'.dependencies]
crossterm = { version = "0.29.0", default-features = false, features = ["bracketed-paste", "events", "windows"], optional = true }
