[package]
name = "kursor"
authors.workspace = true
categories.workspace = true
description = "Compose reactive terminal interfaces effortlessly"
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
readme = "../README.md"

[lib]
crate-type = ["lib"]

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm"]
termina = ["dep:termina"]
animate = ["kursor-core/animate", "dep:animate"]
fx = ["dep:kursor-fx", "animate"]

[dependencies]
# internal
kursor-core = { version = "0.1.0", path = "../kursor-core" }
kursor-fx = { version = "0.1.0", path = "../kursor-fx", optional = true }

# backend
crossterm = { version = "0.29.0", default-features = false, features = ["bracketed-paste", "events"], optional = true }
termina = { version = "0.3.3", optional = true }

unicode-width = "0.2"
animate = { version = "0.5", optional = true, default-features = false }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
crossterm = { version = "0.29.0", default-features = false, features = ["bracketed-paste", "events", "windows"], optional = true }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Threading"] }